### ISSUE TITLE
Did the Headsharp C# Third Edition Kindle eBook Get Pulled from Amazon?

### ISSUE THREAD

**Issue by narniaexpert** [head-first-csharp/third-edition#2]
I have been going through this book as a Kindle Library Loan, but now when I go to redeem the ebook Amazon says "Sorry, this book is not currently available. Please return to your library to see if you can check out the book in a different format." When I search for "Head First C#: A Learner's Guide to Real-World Programming with C#, XAML, and .NET" in the Kindle store there are no results. Did this book get pulled from Amazon's Kindle Store?

**Comment by andrewstellman** [comment]
Hi, David! Honestly, I'm not sure. I see you're on Twitter – please DM me @[AndrewStellman](https://twitter.com/AndrewStellman) and I'll help you out.
